
# the Makfile for all the cpp about chapter 8 and chapter 9

edit: main.o cpp4.o
	g++ -o edit main.o cpp4.o

main.o: main.cpp head.h
	g++ -c main.cpp

cpp4.o: cpp4.cpp head.h
	g++ -c cpp4.cpp


clean:
	rm edit main.o cpp4.o

